### PR TITLE
WIP: Import of MRP prototype

### PR DESCRIPTION
**Pull request by postlund**
A lot of work is being done by me in order to implement MRP. This PR will be used as an open development space with all the (raw) code for the protocol. Changes will be pushed whenever I do something new.

From commit message:
```
This is the MRP prototype. It is not usable for anything, it just shows
how the pairing process is performed and how to encrypt/decrypt
messages correctly. It's also a mess and I will continue refactoring
as I get time to do so but I would like to share the code until then.

To try it out, just use:

   atvremote --debug --protocol mrp -a pair

Add --address in case you want to target a specific device (but you
must still use -a to discover the correct port).
```

### CODE REVIEW

**Comment by postlund** [comment]
It is now possible to scan for devices and also pair correctly with an MRP device. Example of scanning:
```
$ atvremote scan
Device "iOS Simulator" at 10.0.10.50 supports these services:
 - Protocol: MRP, Port: 59911, Device Credentials: None

Device "Apple TV" at 10.0.10.81 supports these services:
 - Protocol: DMAP, Port: 3689, Device Credentials: XXXX
 - Protocol: AirPlay, Port: 7000

Note: You must use 'pair' with devices that have home sharing disabled
```
_Note: The concept of "login id" has now been renamed to "device credentials instead. It is not updated everywhere yet, but I'm working on it._

To pair with a specific MRP device:
```
$ atvremote --protocol mrp --address 10.0.10.50 -a pair
Enter PIN on screen: 9691
Pairing seems to have succeeded, yey!
You may now use these credentials: c75a0a43e931e43a0c74da81b1388eef048bbaacdc0eec1a7e1a3bbb6e76daf2:1b6bbf5288696f65a31d0bf8f41bd1f6545a94a3dea49206aea468792718f23f:39633731323036382d626238642d343262652d386364332d323164643463383362323430:33393039386532372d666661342d343135332d626138322d393137643561633534663338
```
No commands are currently implemented, I have focused on device management so far. But the "stop" command will subscribe to various device updates and idle for 100 seconds. Raw data is printed to console if ``--debug`` is used. Just specify the long credentials string from ``pair``as the new parameter ``--device_credentials`` when calling a command:
```
$ atvremote --debug --protocol mrp --address 10.0.10.50 -a --device_credentials c75a0a43e931e43a0c74da81b1388eef048bbaacdc0eec1a7e1a3bbb6e76daf2:1b6bbf5288696f65a31d0bf8f41bd1f6545a94a3dea49206aea468792718f23f:39633731323036382d626238642d343262652d386364332d323164643463383362323430:33393039386532372d666661342d343135332d626138322d393137643561633534663338 stop
DEBUG: Discovering devices for 3 seconds
DEBUG: Auto-discovered iOS Simulator at 10.0.10.50:59911 (protocol: 2)
DEBUG: Aborting since a device was found
INFO: Auto-discovered iOS Simulator at 10.0.10.50
DEBUG: >> Send (Data=080f122433346263393637632d643031652d343966332d616436302d3466656432363037313735662000a2015a0a2433393039386532372d666661342d343135332d626138322d393137643561633534663338120570796174761a066950686f6e65220531344736302a12636f6d2e6170706c652e545652656d6f746532063237332e31323801)
DEBUG: >> Send: Protobuf=type: DEVICE_INFO_MESSAGE
identifier: "34bc967c-d01e-49f3-ad60-4fed2607175f"
priority: 0
[deviceInfoMessage] {
  uniqueIdentifier: "39098e27-ffa4-4153-ba82-917d5ac54f38"
  name: "pyatv"
  localizedModelName: "iPhone"
  systemBuildVersion: "14G60"
  applicationBundleIdentifier: "com.apple.TVRemote"
  applicationBundleVersion: "273.12"
  protocolVersion: 1
}

DEBUG: MRP message receiver started
DEBUG: Waiting for new message...
DEBUG: << Receive (Data=8e01080f122433346263393637632d643031652d343966332d616436302d3466656432363037313735662000a201610a2431443235314431422d393831302d343334462d384244422d394530333236343934453335120d694f532053696d756c61746f721a034d6163220531364732392a16636f6d2e6170706c652e6d6564696172656d6f7465643801402d48015001)
DEBUG: << Receive: Protobuf=type: DEVICE_INFO_MESSAGE
identifier: "34bc967c-d01e-49f3-ad60-4fed2607175f"
priority: 0
[deviceInfoMessage] {
  uniqueIdentifier: "1D251D1B-9810-434F-8BDB-9E0326494E35"
  name: "iOS Simulator"
  localizedModelName: "Mac"
  systemBuildVersion: "16G29"
  applicationBundleIdentifier: "com.apple.mediaremoted"
  protocolVersion: 1
}

DEBUG: Waiting for new message...
DEBUG: >> Send (Data=08222000ba02290a250601010320ce2baaea56cc02ddfec7eab5994b99c7f5cf86f608c44712fc4ee1dc0ed561781000)
DEBUG: >> Send: Protobuf=type: CRYPTO_PAIRING_MESSAGE
priority: 0
[cryptoPairingMessage] {
  pairingData: "\006\001\001\003 \316+\252\352V\314\002\335\376\307\352\265\231K\231\307\365\317\206\366\010\304G\022\374N\341\334\016\325ax"
  status: 0
}

DEBUG: << Receive (Data=b20108222000ba02aa010a9f010578bbb7351d623a33168dbd4065703749f6089355d6adcde73a78de2827d601da5b50c9f56c203f4a753bf05da6980f878ba0dad74f246c422507366e926d543a27e3261a89ad306fd47d7b549e600bcc48c8a20d96d02df43f85b9928a3d4a4d79f04757d55de6887b8b7d273349d0fb57850d7c21e91195000601020320111423fc17228ad0916fc4876a6a674edc10aecf20833f460a86e54c4b9dc6081000180020002800)
DEBUG: << Receive: Protobuf=type: CRYPTO_PAIRING_MESSAGE
priority: 0
[cryptoPairingMessage] {
  pairingData: "\005x\273\2675\035b:3\026\215\275@ep7I\366\010\223U\326\255\315\347:x\336(\'\326\001\332[P\311\365l ?Ju;\360]\246\230\017\207\213\240\332\327O$lB%\0076n\222mT:\'\343&\032\211\2550o\324}{T\236`\013\314H\310\242\r\226\320-\364?\205\271\222\212=JMy\360GW\325]\346\210{\213}\'3I\320\373W\205\r|!\351\021\225\000\006\001\002\003 \021\024#\374\027\"\212\320\221o\304\207jjgN\334\020\256\317 \203?F\n\206\345LK\235\306\010"
  status: 0
}

DEBUG: Waiting for new message...
DEBUG: Device (Public=c75a0a43e931e43a0c74da81b1388eef048bbaacdc0eec1a7e1a3bbb6e76daf2, Encrypted=bbb7351d623a33168dbd4065703749f6089355d6adcde73a78de2827d601da5b50c9f56c203f4a753bf05da6980f878ba0dad74f246c422507366e926d543a27e3261a89ad306fd47d7b549e600bcc48c8a20d96d02df43f85b9928a3d4a4d79f04757d55de6887b8b7d273349d0fb57850d7c21e9119500)
DEBUG: >> Send (Data=08222000ba0281010a7d0578b6119753e401ad83c7c08b7363c83de4dc867e6555306f4a6d453c1cf905b9a6cc6f06a97f5189116186c169225c9e281f21e5f30cf68fd279907f3dea78080f51c05c8d092233658af595b535ef988c5e2342fe032ce2e750c3e2cb5385daa3ea21198b868dd6f2ead74eba672507a47d1b7023a2d1a1e20601031000)
DEBUG: >> Send: Protobuf=type: CRYPTO_PAIRING_MESSAGE
priority: 0
[cryptoPairingMessage] {
  pairingData: "\005x\266\021\227S\344\001\255\203\307\300\213sc\310=\344\334\206~eU0oJmE<\034\371\005\271\246\314o\006\251\177Q\211\021a\206\301i\"\\\236(\037!\345\363\014\366\217\322y\220\177=\352x\010\017Q\300\\\215\t\"3e\212\365\225\2655\357\230\214^#B\376\003,\342\347P\303\342\313S\205\332\243\352!\031\213\206\215\326\362\352\327N\272g%\007\244}\033p#\242\321\241\342\006\001\003"
  status: 0
}

DEBUG: << Receive (Data=1408222000ba020d0a030601041000180020002800)
DEBUG: << Receive: Protobuf=type: CRYPTO_PAIRING_MESSAGE
priority: 0
[cryptoPairingMessage] {
  pairingData: "\006\001\004"
  status: 0
}

DEBUG: Waiting for new message...
DEBUG: Keys (Input=ec8602a9c29b5f7f919d5a0307b355d79b83027546d15dd6a4e6e266797c824f, Output=dc07beb64804fb6f8d3bcddb033f2e9caa26caeca3ab347e7afe9220fa18dce9)
DEBUG: >> Send (Data=08102000aa01080801100118012001)
DEBUG: >> Send (Encrypted=d528487c80c65e0f3c7565edbe52a5f8b7dfc952535051b930556b91872f42)
DEBUG: >> Send: Protobuf=type: CLIENT_UPDATES_CONFIG_MESSAGE
priority: 0
[clientUpdatesConfigMessage] {
  artworkUpdates: true
  nowPlayingUpdates: true
  volumeUpdates: true
  keyboardUpdates: true
}

DEBUG: << Receive (Data=443f25bd3f4f88f40965ced22a2169f0175135a0540e0c7dd2556c8392e34574655102133b729fb844e62dc054da2fb30307fae7c71ac39eea48d87c1dd03ae94aa5a789da)
DEBUG: << Receive (Decrypted=080b200082012d0a2b6b4d5254656c65766973696f6e52656d6f74654e6f77506c6179696e67417274776f726b4368616e676564)
DEBUG: << Receive: Protobuf=type: NOTIFICATION_MESSAGE
priority: 0
[notificationMessage] {
  notification: "kMRTelevisionRemoteNowPlayingArtworkChanged"
}

DEBUG: Waiting for new message...
DEBUG: << Receive (Data=19eb091fec9728918b318a731c9966db067d4165b76465cdf6a4)
DEBUG: << Receive (Decrypted=08112000b201020800)
DEBUG: << Receive: Protobuf=type: VOLUME_CONTROL_AVAILABILITY_MESSAGE
priority: 0

DEBUG: Waiting for new message...
DEBUG: << Receive (Data=1a71fc1fc893ce82b196a42b8479774637d59a44f9d84dee8a9df516e8fccf5e6008c01e726b34680834b0f5f138f52895a7448bb2e7b616f5b112af95dd4a8dc6eccf2e31a56f11fe56fbd4c92b19df83c4e7bb3fecdf03ce66356cdc766f563da0b25d6573d744a570fad54787ff6183521c182f42cd)
DEBUG: << Receive (Decrypted=080420004a0412003002)
DEBUG: << Receive: Protobuf=type: SET_STATE_MESSAGE
priority: 0

DEBUG: Waiting for new message...
DEBUG: << Receive (Data=16093fc8847928ac5ec9534fe02a6456064fe0cf76cbb9)
DEBUG: << Receive (Decrypted=080520005200)
DEBUG: << Receive: Protobuf=type: SET_ARTWORK_MESSAGE
priority: 0

DEBUG: Waiting for new message...
```
New messages printed automatically.

**Comment by postlund** [comment]
I finally bought an Apple TV 4K, so it's easier to experiment now. Pairing worked flawlessly and doing the trick above ("stop" command) results in this state change:
```
DEBUG: Waiting for new message...
DEBUG: << Receive (Data=e601eb9546affad862ab7b811f6dab03ca28c01454e2f07b3edc20a869a096ade354db565114cd689c3b331893d9c6860c8be484eb2ed1a5000b5a4202ebe7556d5ed89a47360754d07469954d56afb234d5d7aa6c0b78e44d39a80375a1e771605febf22578959f31448cb86df3e7c417718bdd3136d19e33a95d12c349dd99182274cc0125485e0d376721b512af569f1ba221756f8ef2ef02b28e906f9759325477f97bae590438dd7ac7b98591b73d67a960dc47bd556923d0928229431951a5acc7cd42781e6972b51ffe8318359ba8b398550d0678c8107866e42643d7c95815e3031a1aef)
DEBUG: << Receive (Decrypted=080420004acf010a4619925cfe43fac1a44021a97e1548ea95a0402d0000803f41a93119bcaf86bf414a16426f6e64652073c3b66b6572206672752064656c203250d4ade883feffffffff0188010012690a04080110010a04080210010a04080310010a04083510010a04083610010a04080410010a04081210010a04081310010a04080910010a04080b10010a04081410010a07082d10018001000a04082210010a04082310010a04083810010a04083710010a0408391001220e73652e7476342e747634706c61792a0854563420506c61793001)
DEBUG: << Receive: Protobuf=type: SET_STATE_MESSAGE
priority: 0
```
Decoding the raw data looks like this:
```
$ echo -n "080420004acf010a4619925cfe43fac1a44021a97e1548ea95a0402d0000803f41a93119bcaf86bf414a16426f6e64652073c3b66b6572206672752064656c203250d4ade883feffffffff0188010012690a04080110010a04080210010a04080310010a04083510010a04083610010a04080410010a04081210010a04081310010a04080910010a04080b10010a04081410010a07082d10018001000a04082210010a04082310010a04083810010a04083710010a0408391001220e73652e7476342e747634706c61792a0854563420506c61793001" | tr -d ' ' | xxd -r -p | protoc --decode_raw
1: 4
4: 0
9 {
  1 {
    3: 0x40a4c1fa43fe5c92
    4: 0x40a095ea48157ea9
    5: 0x3f800000
    8: 0x41bf86afbc1931a9
    9: "Bonde s\303\266ker fru del 2"
    10: 18446744073180681940
    17: 0
  }
  2 {
    1 {
      1: 1
      2: 1
    }
    1 {
      1: 2
      2: 1
    }
    1 {
      1: 3
      2: 1
    }
    1 {
      1: 53
      2: 1
    }
    1 {
      1: 54
      2: 1
    }
    1 {
      1: 4
      2: 1
    }
    1 {
      1: 18
      2: 1
    }
    1 {
      1: 19
      2: 1
    }
    1 {
      1: 9
      2: 1
    }
    1 {
      1: 11
      2: 1
    }
    1 {
      1: 20
      2: 1
    }
    1 {
      1: 45
      2: 1
      16: 0
    }
    1 {
      1: 34
      2: 1
    }
    1 {
      1: 35
      2: 1
    }
    1 {
      1: 56
      2: 1
    }
    1 {
      1: 55
      2: 1
    }
    1 {
      1: 57
      2: 1
    }
  }
  4: "se.tv4.tv4play"
  5: "TV4 Play"
  6: 1
}
```
Lots of stuff there, but it's quite easy to see what's playing and which app it is. Just need to reverse engineer the actual meaning of everything but it's looking good!

NB: I didn't pick the program ;-)

**Comment by postlund** [comment]
Some additional progress... It's quite time consuming to decode messages, but I think I figured ``SET_STATE_MESSAGE`` above. A decoded version looks like this:
```
$ ./scripts/print_protobuf.py 080420004acf010a4619925cfe43fac1a44021a97e1548ea95a0402d0000803f41a93119bcaf86bf414a16426f6e64652073c3b66b6572206672752064656c203250d4ade883feffffffff0188010012690a04080110010a04080210010a04080310010a04083510010a04083610010a04080410010a04081210010a04081310010a04080910010a04080b10010a04081410010a07082d10018001000a04082210010a04082310010a04083810010a04083710010a0408391001220e73652e7476342e747634706c61792a0854563420506c61793001
type: SET_STATE_MESSAGE
priority: 0
[setStateMessage] {
  nowPlayingInfo {
    duration: 2656.9888
    elapsedTime: 2122.957581207
    timestamp: 528920508.098414
    title: "Bonde s\303\266ker fru del 2"
    uniqueIdentifier: 18446744073180681940
    isAlwaysLive: 0
  }
  supportedCommands {
    supportedCommand {
      command: Play
      enabled: true
    }
    supportedCommand {
      command: Pause
      enabled: true
    }
    supportedCommand {
      command: TogglePlayPause
      enabled: true
    }
    supportedCommand {
      command: EnableLanguageOption
      enabled: true
    }
    supportedCommand {
      command: DisableLanguageOption
      enabled: true
    }
    supportedCommand {
      command: Stop
      enabled: true
    }
    supportedCommand {
      command: SkipForward
      enabled: true
    }
    supportedCommand {
      command: SkipBackward
      enabled: true
    }
    supportedCommand {
      command: BeginFastForward
      enabled: true
    }
    supportedCommand {
      command: BeginRewind
      enabled: true
    }
    supportedCommand {
      command: ChangePlaybackRate
      enabled: true
    }
    supportedCommand {
      command: SeekToPlaybackPosition
      enabled: true
      canScrub: false
    }
    supportedCommand {
      command: NextInContext
      enabled: true
    }
    supportedCommand {
      command: PreviousInContext
      enabled: true
    }
    supportedCommand {
      command: RemoveFromPlaybackQueue
      enabled: true
    }
    supportedCommand {
      command: ReorderPlaybackQueue
      enabled: true
    }
    supportedCommand {
      command: PlayItemInPlaybackQueue
      enabled: true
    }
  }
  displayID: "se.tv4.tv4play"
  displayName: "TV4 Play"
  playbackState: 1
}
```
I have added some prototype code (that I will have to re-write later) to test out ``playing``:
```
$ atvremote --debug -a --protocol mrp --address 10.0.10.104 --device_credentials `cat creds` playing
Media type: Unknown
Play state: Playing
     Title: Halv åtta hos mig del 28
  Position: 0/1326s (0.0%)
```
Play position is not calculated correctly but a comment is in the code on how to do it (just don't have time to fix it now).

There are a lot of messages going back and forth, so it will take some time to finish the implementation. But now I basically know how to do it so it should make things easier.

Note-to-self: submit SetStateMessage to https://github.com/jeanregisser/mediaremotetv-protocol (@jeanregisser, you might be interested in this).

**Comment by postlund** [comment]
Current code can do most things no, but not everything is implemented. Some metadata is missing, artwork does not work as well as shuffle and repeat. But the general skeleton is in place. I also added a small CLI by issuing command "cli":
```
$ atvremote --address 10.0.10.104 --device_credentials `cat creds` --protocol mrp --port 53688 cli
Enter commands and press enter
Type help for help and exit to quit
pyatv> playing
Media type: Unknown
Play state: Playing
     Title: Historieätarna – Säsong 1, Avsnitt 4, Det glada 1920-talet
  Position: 267/6832s (3.9%)
pyatv> title
Historieätarna – Säsong 1, Avsnitt 4, Det glada 1920-talet
pyatv> stop
pyatv> play
pyatv> exit
```
There are some underlying bugs that must be sorted out. I believe that I send something the device doesn't like and stops responding. Need to investigate that further. But I'm making lots of progress!

**Comment by thejjmiller** [comment]
Looks really good! Any chance you could figure out how to send long hold button presses. I'm interesting in figuring out how to turn the TV off with this. If I can long press the top_menu button and then select a second later i can sleep the tv

**Comment by postlund** [comment]
There is no such thing as a "long hold", that's just a construct in the remote app/on the physical remote. It is mapped to some other command in the end. AFAIK it's not possible to turn a device off that way using this protocol, but there's a real support for standby anyway so it's not really needed. Navigating through menus would be considered a hack.

I wrote something about sleeping in https://github.com/lprhodes/homebridge-apple-tv/issues/3 a while back. Unfortunately working on pyatv is not my top-priority right now so it will probably take a while until I can finish this.

**Pull request merged**
