### PR TITLE
Simplify ChaCha20 Poly1305 implementation

### PR DESCRIPTION
**Pull request by bdraco**
similar change to
https://github.com/esphome/aioesphomeapi/blob/c9227edf7fcee0f175c9f31c024ba71b0a0fac26/aioesphomeapi/_frame_helper/noise.py#L31
https://github.com/ikalchev/HAP-python/blob/dev/pyhap/hap_crypto.py#L17

`pack` is a bit faster than `to_bytes`

### CODE REVIEW

**Comment by bdraco** [comment]
Thanks for the 👀

**Comment by postlund** [comment]
This unfortunately breaks Companion that uses 12 bytes as nonce length 😳

**Comment by bdraco** [comment]
No worries, guess we need to revert. Sorry I missed that.

**Comment by bdraco** [comment]
I guess we could subclass it instead and have a separate fast pack for that

**Comment by bdraco** [comment]
https://github.com/postlund/pyatv/pull/2412

**Pull request merged**
