### PR TITLE
Make sure were sending and receiving volume messages for our device

### PR DESCRIPTION
**Pull request by michalmo**
… even if playing to other AirPlay devices in a group.

Fixes: #2005

Instead of updating `self._output_device_id` when we get a `VOLUME_CONTROL_CAPABILITIES_DID_CHANGE_MESSAGE` (which may be the UID of another grouped AirPlay device), just always use the one from device info which we get when the protocol starts.

### CODE REVIEW

**Comment by postlund** [comment]
This looks reasonable to me, will merge it when it passes. I didn't find the time to make a release yesterday, but I can make it now pretty much. Is there anything else you want to have merged before the release?

**Comment by michalmo** [comment]
Just this one will allow me to make the changes to HA.

#1905 is still open when you have some time, but that can be later.

**Comment by JonLaliberte** [comment]
I'm wondering if this would also resolve #1838 ?

**Comment by michalmo** [comment]
I'll answer in that issue, since there's quite a bit of detail.

**Pull request merged**
