### PR TITLE
Add support for pairing

### PR DESCRIPTION
**Pull request by postlund**
Should work by using atvremote:

    atvremote pair

And then add the remote on the Apple TV. Default pin is 1234 (which
must be correctly entered) and name is "pyatv remote". These settings
can be changed with parameters to atvremote. Currently a pairing
timer is set to 60 seconds, so the process must be finished within
that time.

NOTE: Before merging this, some work must be done with tearing down the webserver and zeroconf after the paring period is done. It currently leaks.

### CODE REVIEW

**Comment by robbiet480** [comment]
I paired it but when using the login ID a 503 was thrown.

**Comment by postlund** [comment]
What does the URLs look like?

**Comment by robbiet480** [comment]
```
(pyatv) HomeAssistant/pyatv [ atvremote --address 192.168.1.214 --login_id 0000000000000001 --debug commands                                                                    pairing_process * ] 2:19 PM
DEBUG: GET URL: http://192.168.1.214:3689/login?hsgid=0000000000000001&hasFP=1
DEBUG: Data[3]: b'313033'
WARNING: Unknown data: b'103'
DEBUG: get_data: 103: None [_unknown, unknown tag]

DEBUG: GET URL: http://192.168.1.214:3689/login?hsgid=0000000000000001&hasFP=1
DEBUG: Data[3]: b'313033'
WARNING: Unknown data: b'103'
DEBUG: get_data: 103: None [_unknown, unknown tag]

Traceback (most recent call last):
  File "/Users/robbiet480/Repos/HomeAssistant/pyatv/pyatv/__main__.py", line 245, in _run_application
    asyncio.wait_for((yield from cli_handler(loop)), timeout=15)
  File "/Users/robbiet480/Repos/HomeAssistant/pyatv/pyatv/__main__.py", line 96, in cli_handler
    return (yield from _handle_command(args, loop))
  File "/Users/robbiet480/Repos/HomeAssistant/pyatv/pyatv/__main__.py", line 173, in _handle_command
    playing_resp = yield from atv.metadata.playing()
  File "/Users/robbiet480/Repos/HomeAssistant/pyatv/pyatv/internal/apple_tv.py", line 225, in playing
    playstatus = yield from self.apple_tv.playstatus()
  File "/Users/robbiet480/Repos/HomeAssistant/pyatv/pyatv/daap.py", line 126, in get
    yield from self._assure_logged_in()
  File "/Users/robbiet480/Repos/HomeAssistant/pyatv/pyatv/daap.py", line 177, in _assure_logged_in
    yield from self.login()
  File "/Users/robbiet480/Repos/HomeAssistant/pyatv/pyatv/daap.py", line 115, in login
    resp = yield from self._do(self.session.get_data, url)
  File "/Users/robbiet480/Repos/HomeAssistant/pyatv/pyatv/daap.py", line 152, in _do
    action, url, False, is_login=is_login, is_daap=is_daap))
  File "/Users/robbiet480/Repos/HomeAssistant/pyatv/pyatv/daap.py", line 155, in _do
    'failed to login: ' + str(status))
pyatv.exceptions.AuthenticationError: failed to login: 503

>>> An error occurred, full stack trace above
```

**Comment by postlund** [comment]
Try adding 0x in front of the login id. I should make that more clear.

**Comment by robbiet480** [comment]
All good now. I figured that you were adding the `0x` in the code so I hadn't added it myself.

**Comment by postlund** [comment]
Good 👍  For some reason I decided not to do that. I use a regex to decide if the identifier is a HSGID or pairing-guid, which requires 0x. Then I just pass the id along. Guess it was simple that way.

**Pull request merged**
