### PR TITLE
WIP: Prototype keyboard input

### PR DESCRIPTION
**Pull request by postlund**
This does not seem to work yet but can act as a base in case we find out
what is wrong...

### CODE REVIEW

**Comment by masikh** [comment]
I made a new capture (crestron module to atv 4)

**Comment by masikh** [comment]
[ATV Gen 4&5 Hex Dump.zip](https://github.com/postlund/pyatv/files/2071598/ATV.Gen.4.5.Hex.Dump.zip)

**Comment by masikh** [comment]
It seems to me we first need to call this function (daap.py)
    @asyncio.coroutine
    def get(self, cmd, daap_data=True, timeout=None, **args):
        """Perform a DAAP GET command."""
        def _get_request():
            return self.http.get_data(
                self._mkurl(cmd, *args),
                headers=_DMAP_HEADERS,
                timeout=timeout)

        yield from self._assure_logged_in()
        return (yield from self._do(_get_request, is_daap=daap_data))

with cmd == 'ctrl-int/1/controlpromptupdate?[AUTH]&prompt-id=1'

which yields something like:

[{'cmcp': [{'mstt': 200}, {'miid': 926}, {'mdcl': [{'cmce': 'kKeybMsgKey_String'}, {'cmcv': '308202C33082022CA003020102020D3333AF080604AF0001AF000001300D06092A864886F70D0101050500307B310B300906035504061302555331133011060355040A130A4170706C6520496E632E31263024060355040B131D4170706C652043657274696669636174696F6E20417574686F72697479312F302D060355040313264170706C652046616972506C61792043657274696669636174696F6E20417574686F72697479301E170D3038303630343231333030315A170D3133303630333231333030315A3066310B300906035504061302555331133011060355040A130A4170706C6520496E632E31173015060355040B130E4170706C652046616972506C61793129302706035504031320526F7369652E333333334146303830363034414630303031414630303030303130819F300D06092A864886F70D010101050003818D0030818902818100DCB60285A26C6B4DE502C49C842A527176C0185B082DCE6C646B55A2640706A6967DED8F23C8542E284107A9A22709E1056E934BC3C4F01798BD54391829490665205F296E9BE2595E0419AEDEDA77D44560CC7AF1E3A72F37EFE9AED51263ED0807FED2CCB723F51D08CD8DFB41F675770671E03C29E29E39C53161057453BD0203010001A360305E300E0603551D0F0101FF0404030203B8300C0603551D130101FF04023000301D0603551D0E041604148F4E4787070D6D84FD1F307932107EBC04CEAC55301F0603551D23041830168014FA0DD411911BE6B24E1E06499411DD6362075964300D06092A864886F70D010105050003818100153F2F1572D279E5DB1E1776CCA603131D7788B598BD1EFC7C1703A40A06C905C762CE1665440912A1BCA88F766861C436543A1A9AB536DEB479BF2803F383E92A75B7360B47B8197387A6BB4EB82554C6762C06C4E236A890139396F56138C1B69395FCFED8CB74BF94D91E0E98F6F8276A2B49172847498A5843847ED00FC8'}]}, {'mdcl': [{'cmce': 'kKeybMsgKey_SessionID'}, {'cmcv': '298'}]}, {'mdcl': [{'cmce': 'kKeybMsgKey_KeyboardType'}, {'cmcv': '0'}]}, {'mdcl': [{'cmce': 'kKeybMsgKey_Version'}, {'cmcv': '0'}]}, {'mdcl': [{'cmce': 'kKeybMsgKey_MaxCharacters'}, {'cmcv': '0'}]}, {'mdcl': [{'cmce': 'kKeybMsgKey_MessageType'}, {'cmcv': '3'}]}, {'mdcl': [{'cmce': 'kKeybMsgKey_SubText'}, {'cmcv': '01576120704EC4F53FAAE27BCB'}]}, {'mdcl': [{'cmce': 'kKeybMsgKey_SecureText'}, {'cmcv': '0'}]}, {'mdcl': [{'cmce': 'kKeybMsgKey_MinCharacters'}, {'cmcv': '0'}]}, {'mdcl': [{'cmce': 'kKeybMsgKey_TextInputType'}, {'cmcv': '0'}]}]}]

After which the keyboard command should be called: 

tag building should look like this I guess!

def keyboard_tag(value):
    return 'cmcc'.encode('utf-8') + b'\x00\x00\x00\x01\x39' + \
           'cmbe'.encode('utf-8') + b'\x00\x00\x00\x0c' + \
           'PromptUpdatecmte'.encode('utf-8') + \
           len(value).to_bytes(4, byteorder='big') + value.encode('utf-8')

BUT!!! I assume we also need to do something with the first reply, although I cannot find any evidence for my assumption within the provided wireshark dumps (which are from a working setup, hence the keyboard actually did something as in it showed 'abcde..'

Honestly, I am stuck!

**Comment by postlund** [comment]
I'm gonna abandon this for now and come back with a better solution later.

**Pull request closed without merging**
