### PR TITLE
Add support for companion protocol text input

### LINKED ISSUE #1716: Investigating Companion api Keyboard implementation
### What to investigate?

Find out how to get keyboard updates and send keyboard text through the companion protocol.

So I've started debugging some stuff in the console with my iPhone connected, current progress is that I am able to subscribe to the right events and get actual changes by adding the following in the connect method:
```python
await self.subscribe_event("_tiC") # fired when there's text input changes through on screen keyboard appletv
await self.subscribe_event("_tiStarted") # fired when keyboard is available
await self.subscribe_event("_tiStopped") # fired when keyboard is no longer available
await self._send_command("_tiStart", {}) # starts text input session
```

Now I'm trying to figure out the command to send actual text input. I've found that keyboard presses only send back a _tiC event in the console and I can't seem to figure out yet what the command should be to actually send text.

Some current events:

**_tiStarted**
```
{'_i': '_tiStarted', '_x': 568430212, '_c': {'_tiV': 1, '_tiD': b'bplist00\xd4\x01\x02\x03\x04\x05\x06\x07\x0eX$versionY$archiverT$topX$objects\x12\x00\x01\x86\xa0_\x10\x0fNSKeyedArchiver\xd3\x08\t\n\x0b\x0c\r^documentTraits[sessionUUID]documentState\x80\x06\x80\x0c\x80\x01\xad\x0f\x10\x15\x19\x1a!%/0159=U$null\xd2\x11\x12\x13\x14UdocStV$class\x80\x02\x80\x05\xd2\x16\x12\x17\x18_\x10\x12contextBeforeInput\x80\x03\x80\x04ZTesteraaaa\xd2\x1b\x1c\x1d\x1eZ$classnameX$classes_\x10\x0fTIDocumentState\xa2\x1f _\x10\x0fTIDocumentStateXNSObject\xd2\x1b\x1c"#_\x10\x10RTIDocumentState\xa2$ _\x10\x10RTIDocumentState\xd5&\'()\x12*++-.SbIdSappVlocAppXtiTraits\x80\x07\x80\x08\x80\x08\x80\t\x80\x0b_\x10\x12com.apple.TVSearchVSearch\xd22\x1234Uflags\x12T\x10\x1a\x86\x80\n\xd2\x1b\x1c67_\x10\x11TITextInputTraits\xa28 _\x10\x11TITextInputTraits\xd2\x1b\x1c:;_\x10\x11RTIDocumentTraits\xa2< _\x10\x11RTIDocumentTraitsO\x10\x106\xa7\xfa+\x03\xadL\x1d\xbd\x04\xab\xec\x96:6\x9d\x00\x08\x00\x11\x00\x1a\x00$\x00)\x002\x007\x00I\x00P\x00_\x00k\x00y\x00{\x00}\x00\x7f\x00\x8d\x00\x93\x00\x98\x00\x9e\x00\xa5\x00\xa7\x00\xa9\x00\xae\x00\xc3\x00\xc5\x00\xc7\x00\xd2\x00\xd7\x00\xe2\x00\xeb\x00\xfd\x01\x00\x01\x12\x01\x1b\x01 \x013\x016\x01I\x01T\x01X\x01\\\x01c\x01l\x01n\x01p\x01r\x01t\x01v\x01\x8b\x01\x92\x01\x97\x01\x9d\x01\xa2\x01\xa4\x01\xa9\x01\xbd\x01\xc0\x01\xd4\x01\xd9\x01\xed\x01\xf0\x02\x04\x00\x00\x00\x00\x00\x00\x02\x01\x00\x00\x00\x00\x00\x00\x00>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x17'}, '_t': 1}
2022-04-29 11:46:38 DEBUG [pyatv.protocols.companion.api]: Got event _tiStarted from device: {'_tiV': 1, '_tiD': b'bplist00\xd4\x01\x02\x03\x04\x05\x06\x07\x0eX$versionY$archiverT$topX$objects\x12\x00\x01\x86\xa0_\x10\x0fNSKeyedArchiver\xd3\x08\t\n\x0b\x0c\r^documentTraits[sessionUUID]documentState\x80\x06\x80\x0c\x80\x01\xad\x0f\x10\x15\x19\x1a!%/0159=U$null\xd2\x11\x12\x13\x14UdocStV$class\x80\x02\x80\x05\xd2\x16\x12\x17\x18_\x10\x12contextBeforeInput\x80\x03\x80\x04ZTesteraaaa\xd2\x1b\x1c\x1d\x1eZ$classnameX$classes_\x10\x0fTIDocumentState\xa2\x1f _\x10\x0fTIDocumentStateXNSObject\xd2\x1b\x1c"#_\x10\x10RTIDocumentState\xa2$ _\x10\x10RTIDocumentState\xd5&\'()\x12*++-.SbIdSappVlocAppXtiTraits\x80\x07\x80\x08\x80\x08\x80\t\x80\x0b_\x10\x12com.apple.TVSearchVSearch\xd22\x1234Uflags\x12T\x10\x1a\x86\x80\n\xd2\x1b\x1c67_\x10\x11TITextInputTraits\xa28 _\x10\x11TITextInputTraits\xd2\x1b\x1c:;_\x10\x11RTIDocumentTraits\xa2< _\x10\x11RTIDocumentTraitsO\x10\x106\xa7\xfa+\x03\xadL\x1d\xbd\x04\xab\xec\x96:6\x9d\x00\x08\x00\x11\x00\x1a\x00$\x00)\x002\x007\x00I\x00P\x00_\x00k\x00y\x00{\x00}\x00\x7f\x00\x8d\x00\x93\x00\x98\x00\x9e\x00\xa5\x00\xa7\x00\xa9\x00\xae\x00\xc3\x00\xc5\x00\xc7\x00\xd2\x00\xd7\x00\xe2\x00\xeb\x00\xfd\x01\x00\x01\x12\x01\x1b\x01 \x013\x016\x01I\x01T\x01X\x01\\\x01c\x01l\x01n\x01p\x01r\x01t\x01v\x01\x8b\x01\x92\x01\x97\x01\x9d\x01\xa2\x01\xa4\x01\xa9\x01\xbd\x01\xc0\x01\xd4\x01\xd9\x01\xed\x01\xf0\x02\x04\x00\x00\x00\x00\x00\x00\x02\x01\x00\x00\x00\x00\x00\x00\x00>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x17'}0
```

**_tiStopped**
```
{'_i': '_tiStopped', '_x': 568430233, '_c': {}, '_t': 1}
```

**_tiC**
```
{'_i': '_tiC', '_x': 568430219, '_c': {'_tiV': 1, '_tiD': b'bplist00\xd4\x01\x02\x03\x04\x05\x06\x07\x0eX$versionY$archiverT$topX$objects\x12\x00\x01\x86\xa0_\x10\x0fNSKeyedArchiver\xd3\x08\t\n\x0b\x0c\r^documentTraits[sessionUUID]documentState\x80\x06\x80\x0c\x80\x01\xad\x0f\x10\x15\x19\x1a!%/0159=U$null\xd2\x11\x12\x13\x14UdocStV$class\x80\x02\x80\x05\xd2\x16\x12\x17\x18_\x10\x12contextBeforeInput\x80\x03\x80\x04Qa\xd2\x1b\x1c\x1d\x1eZ$classnameX$classes_\x10\x0fTIDocumentState\xa2\x1f _\x10\x0fTIDocumentStateXNSObject\xd2\x1b\x1c"#_\x10\x10RTIDocumentState\xa2$ _\x10\x10RTIDocumentState\xd5&\'()\x12*++-.SbIdSappVlocAppXtiTraits\x80\x07\x80\x08\x80\x08\x80\t\x80\x0b_\x10\x12com.apple.TVSearchVSearch\xd22\x1234Uflags\x12T\x10\x1a\x86\x80\n\xd2\x1b\x1c67_\x10\x11TITextInputTraits\xa28 _\x10\x11TITextInputTraits\xd2\x1b\x1c:;_\x10\x11RTIDocumentTraits\xa2< _\x10\x11RTIDocumentTraitsO\x10\x106\xa7\xfa+\x03\xadL\x1d\xbd\x04\xab\xec\x96:6\x9d\x00\x08\x00\x11\x00\x1a\x00$\x00)\x002\x007\x00I\x00P\x00_\x00k\x00y\x00{\x00}\x00\x7f\x00\x8d\x00\x93\x00\x98\x00\x9e\x00\xa5\x00\xa7\x00\xa9\x00\xae\x00\xc3\x00\xc5\x00\xc7\x00\xc9\x00\xce\x00\xd9\x00\xe2\x00\xf4\x00\xf7\x01\t\x01\x12\x01\x17\x01*\x01-\x01@\x01K\x01O\x01S\x01Z\x01c\x01e\x01g\x01i\x01k\x01m\x01\x82\x01\x89\x01\x8e\x01\x94\x01\x99\x01\x9b\x01\xa0\x01\xb4\x01\xb7\x01\xcb\x01\xd0\x01\xe4\x01\xe7\x01\xfb\x00\x00\x00\x00\x00\x00\x02\x01\x00\x00\x00\x00\x00\x00\x00>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x0e'}, '_t': 1}
2022-04-29 11:47:10 DEBUG [pyatv.protocols.companion.api]: Got event _tiC from device: {'_tiV': 1, '_tiD': b'bplist00\xd4\x01\x02\x03\x04\x05\x06\x07\x0eX$versionY$archiverT$topX$objects\x12\x00\x01\x86\xa0_\x10\x0fNSKeyedArchiver\xd3\x08\t\n\x0b\x0c\r^documentTraits[sessionUUID]documentState\x80\x06\x80\x0c\x80\x01\xad\x0f\x10\x15\x19\x1a!%/0159=U$null\xd2\x11\x12\x13\x14UdocStV$class\x80\x02\x80\x05\xd2\x16\x12\x17\x18_\x10\x12contextBeforeInput\x80\x03\x80\x04Qa\xd2\x1b\x1c\x1d\x1eZ$classnameX$classes_\x10\x0fTIDocumentState\xa2\x1f _\x10\x0fTIDocumentStateXNSObject\xd2\x1b\x1c"#_\x10\x10RTIDocumentState\xa2$ _\x10\x10RTIDocumentState\xd5&\'()\x12*++-.SbIdSappVlocAppXtiTraits\x80\x07\x80\x08\x80\x08\x80\t\x80\x0b_\x10\x12com.apple.TVSearchVSearch\xd22\x1234Uflags\x12T\x10\x1a\x86\x80\n\xd2\x1b\x1c67_\x10\x11TITextInputTraits\xa28 _\x10\x11TITextInputTraits\xd2\x1b\x1c:;_\x10\x11RTIDocumentTraits\xa2< _\x10\x11RTIDocumentTraitsO\x10\x106\xa7\xfa+\x03\xadL\x1d\xbd\x04\xab\xec\x96:6\x9d\x00\x08\x00\x11\x00\x1a\x00$\x00)\x002\x007\x00I\x00P\x00_\x00k\x00y\x00{\x00}\x00\x7f\x00\x8d\x00\x93\x00\x98\x00\x9e\x00\xa5\x00\xa7\x00\xa9\x00\xae\x00\xc3\x00\xc5\x00\xc7\x00\xc9\x00\xce\x00\xd9\x00\xe2\x00\xf4\x00\xf7\x01\t\x01\x12\x01\x17\x01*\x01-\x01@\x01K\x01O\x01S\x01Z\x01c\x01e\x01g\x01i\x01k\x01m\x01\x82\x01\x89\x01\x8e\x01\x94\x01\x99\x01\x9b\x01\xa0\x01\xb4\x01\xb7\x01\xcb\x01\xd0\x01\xe4\x01\xe7\x01\xfb\x00\x00\x00\x00\x00\x00\x02\x01\x00\x00\x00\x00\x00\x00\x00>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x0e'}
```

### Expected outcome

Have a working keyboard event and a keyboard input method on the companion api.

### PR DESCRIPTION
**Pull request by michalmo**
This PR adds support for interacting with the text in the on screen keyboard using RTI text operations over the Companion protocol. Supported operations are reading the current text, appending text, clearing the text, and replacing the text.

Resolves #1716

### CODE REVIEW

**Comment by postlund** [comment]
Really sorry about the late reply, I'm trying to get on top of things now. Really great work on this though, it will be appreciated by a lot of users!

I have not had time verifying this yet, will try it as soon as I can. But one change I would like right up is introducing a new interface, rather than extending another one since keyboard handling is new. So basically add a `Keyboard` class in `interface.py` and a new property called `keyboard` in `interface.AppleTV` class. This brings a bit of work (extending the the facade for instance), do you think you can manage that?

Also, do you know if there are any events for keyboard updates so we can implement push updates for keyboard changes?

**Comment by michalmo** [comment]
Sure, I'll take a look and ask if anything isn't clear.

> Also, do you know if there are any events for keyboard updates so we can implement push updates for keyboard changes?

From what I've seen through the proxy, the ATV will send send a `_tiC` event (as was discussed in #1716), but only once when the text input is focused. There are no subsequent events sent when the text changes (even the iOS app doesn't stay in sync). You can however send the `_tiStart` command again the get the current text at any time, implemented as text_get, which could be used to poll for updates.

**Comment by michalmo** [comment]
Updated, @postlund let me know if that looks right and I'll rebase the PR on top of master.

**Comment by michalmo** [comment]
So, `plistlib` support for `UID`s, which is required to encode and decode these payloads without some 3rd party library, was [added in python 3.8](https://docs.python.org/3/library/plistlib.html#plistlib.UID). This is why the python 3.7 check is failing.

@postlund do you have a recommendation on how to proceed?

**Comment by postlund** [comment]
@michalmo I will deprecate 3.7 support as soon as I have checks for 3.11 in place. A few other PRs fail for the same reason. So you can just sit tight, hopefully I will have it in place later today.

**Comment by IsakTheHacker** [comment]
Has there been any recent progress for this? When will this by merged into production?

**Comment by postlund** [comment]
It has been my intention to review this properly this week, but it has been extremely busy so I haven't managed. Hopefully really soon.

**Comment by postlund** [comment]
I think we can merge this one as well. A future suggestion though, maybe add a listener interface with like a "focus" event (triggered by `_tiC`) with current text, so a user at least knows when text input is showing. Does that sound reasonable? Is there a corresponding event we could use to detect when a text field no longer shows?

**Comment by michalmo** [comment]
Good idea. There should be an event, the iOS remote app hides the text input when the TV input looses focus. I'll look into it, later.

**Comment by postlund** [comment]
One more thing came to mine that I missed: documentation. A new "Keyboard" page needs to be added with some instructions.

**Pull request merged**
