### PR TITLE
flush output of each line printed by atvscript

### PR DESCRIPTION
**Pull request by dfrommi**
Output-flushing is required to avoid buffering between processes.

Without flush, client applications only receive the output from atvscript
when either a bigger amount of output is generated or the application
terminates.

### CODE REVIEW

**Comment by postlund** [comment]
Yes, you are absolutely right. There are two print's in appstart that you can flush as well (and fix linting by running `black .`). Otherwise good to go!

**Comment by dfrommi** [comment]
Thanks, done.

**Comment by postlund** [comment]
Looks good 👍 Looks like there's some problem with Actions, lets see if it get fixed during the day. Otherwise you can try to force-push again and see if that helps.

**Comment by postlund** [comment]
I have no idea why there's so much problems with GitHub Actions that I haven't seen before. Created a new PR, #552, with the same content to see if it works better. It's so strange.

**Comment by postlund** [comment]
#552 merged correctly, so the changes are in. Sorry about the mess and long lead time here!

**Comment by dfrommi** [comment]
Thanks a lot

**Pull request closed without merging**
