### PR TITLE
AirPlay proxy

### LINKED ISSUE #1252: Add support for AirPlay in atvproxy
**What feature would you like?**
I would like some kind of support for AirPlay in atvproxy so that I can watch the traffic. It needs to work with AirPlay 2.

**Describe the solution you'd like**
It should work like the other protocols in the proxy. At the moment, signaling is what's important. Support for streaming audio isn't strictly needed (I think).

**Any other information to share?**
This is a bit tricky as AirPlay 2 isn't really supported by pyatv yet, so I will have to add the necessary bits. For now I will settle for transient pairing, supported by the HomePod.

### PR DESCRIPTION
**Pull request by michalmo**
Pushing this PR since it's in a state that is working well for me, but may conflict with the work you are doing in #2036. I'll take a look at any potential conflicts later.

Resolves #1252

### CODE REVIEW

**Comment by postlund** [comment]
Awesome! I will have a look at this tomorrow for sure. Anything you want to change before merging it (in case it's ok)?

**Comment by michalmo** [comment]
It's complete other than the test failure on Python 3.8.

I'm using it to do #1939 so I might discover new messages with identifiers that need rewriting, but I can add them later.

**Comment by postlund** [comment]
This is a really big and impressive change, so it's hard to give it a through review. But I've skimmed it and it looks good! Some nice refactoring and clean ups as, much appreciated 👍 

When I'm trying the proxy, I get this error however:

```
2023-06-09 14:25:55 DEBUG [pyatv.scripts.atvproxy]: Client connected to AirPlay proxy
2023-06-09 14:25:55 DEBUG [pyatv.support.http]: Received: b'GET /info RTSP/1.0\r\nX-Apple-ProtocolVersion: 1\r\nContent-Length: 70\r\nContent-Type: application/x-apple-binary-plist\r\nCSeq: 0\r\nUser-Agent: AirPlay/690.7.1\r\n\r\nbplist00\xd1\x01\x02Yqualifier\xa1\x03ZtxtAirPlay\x08\x0b\x15\x17\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"'
2023-06-09 14:25:55 DEBUG [pyatv.scripts.atvproxy]: Request: HttpRequest(method='GET', path='/info', protocol='RTSP', version='1.0', headers={'X-Apple-ProtocolVersion': '1', 'Content-Length': '70', 'Content-Type': 'application/x-apple-binary-plist', 'CSeq': '0', 'User-Agent': 'AirPlay/690.7.1'}, body=b'bplist00\xd1\x01\x02Yqualifier\xa1\x03ZtxtAirPlay\x08\x0b\x15\x17\x00\x00\x00\x00\x00\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"')
2023-06-09 14:25:55 DEBUG [pyatv.scripts.atvproxy]: RTSP request plist content: {'qualifier': ['txtAirPlay']}
2023-06-09 14:25:55 DEBUG [pyatv.support.http]: Connected to 10.0.10.81
2023-06-09 14:25:55 DEBUG [pyatv.protocols.airplay.auth]: Setting up new AirPlay Pair-Verify procedure with type AuthenticationType.Legacy
2023-06-09 14:25:55 DEBUG [pyatv.protocols.airplay.srp]: Authentication keys (Private=499fd1578735b8d1a2d92807639a1e359aaf197d150747f430b1389431db4b13, Public=fb4783f95329b18031e5597ace481a11f896e5f5a73926ab5b21604c02766b39)
2023-06-09 14:25:55 DEBUG [pyatv.protocols.airplay.srp]: Verification keys (Private=499fd1578735b8d1a2d92807639a1e359aaf197d150747f430b1389431db4b13, Public=149370c3491fbcf9ec779cf596a098b9d289623268d5500bf9ddf3295a61c94d)
2023-06-09 14:25:55 DEBUG [pyatv.support.http]: Sending HTTP/1.1 message: b'POST /pair-verify HTTP/1.1\r\nContent-Length: 68\r\nUser-Agent: AirPlay/320.20\r\nConnection: keep-alive\r\nContent-Type: application/octet-stream\r\n\r\n\x01\x00\x00\x00\x14\x93p\xc3I\x1f\xbc\xf9\xecw\x9c\xf5\x96\xa0\x98\xb9\xd2\x89b2h\xd5P\x0b\xf9\xdd\xf3)Za\xc9M\xfbG\x83\xf9S)\xb1\x801\xe5Yz\xceH\x1a\x11\xf8\x96\xe5\xf5\xa79&\xab[!`L\x02vk9'
2023-06-09 14:25:55 DEBUG [pyatv.support.http]: Received: b'HTTP/1.1 500 Internal Server Error\r\nContent-Length: 0\r\nServer: AirTunes/690.7.1\r\n\r\n'
2023-06-09 14:25:55 DEBUG [pyatv.support.http]: Got HTTP response: HttpResponse(protocol='HTTP', version='1.1', code=500, message='Internal Server Error', headers={'Content-Length': '0', 'Server': 'AirTunes/690.7.1'}, body=''):
2023-06-09 14:25:55 ERROR [asyncio]: Task exception was never retrieved
future: <Task finished name='Task-9' coro=<AirPlayAppleTVProxy.start() done, defined at /home/postlund/pyatv_dev/pyatv/pyatv/scripts/atvproxy.py:964> exception=HttpError('HTTP/1.1 method POST failed with code 500: Internal Server Error')>
Traceback (most recent call last):
  File "/home/postlund/pyatv_dev/pyatv/pyatv/scripts/atvproxy.py", line 967, in start
    self.verifier = await verify_connection(
  File "/home/postlund/pyatv_dev/pyatv/pyatv/protocols/airplay/auth/__init__.py", line 104, in verify_connection
    has_encryption_keys = await verifier.verify_credentials()
  File "/home/postlund/pyatv_dev/pyatv/pyatv/protocols/airplay/auth/legacy.py", line 98, in verify_credentials
    resp = await self._send(self.srp.verify1())
  File "/home/postlund/pyatv_dev/pyatv/pyatv/protocols/airplay/auth/legacy.py", line 108, in _send
    return await self.http.post("/pair-verify", headers=headers, body=data)
  File "/home/postlund/pyatv_dev/pyatv/pyatv/support/http.py", line 391, in post
    return await self.send_and_receive(
  File "/home/postlund/pyatv_dev/pyatv/pyatv/support/http.py", line 446, in send_and_receive
    raise exceptions.HttpError(
pyatv.exceptions.HttpError: HTTP/1.1 method POST failed with code 500: Internal Server Error
```
Any idea?

**Comment by michalmo** [comment]
```
2023-06-09 14:25:55 DEBUG [pyatv.protocols.airplay.auth]: Setting up new AirPlay Pair-Verify procedure with type AuthenticationType.Legacy
```
It looks like you've provided legacy credentials, I've only tried it with `AuthenticationType.HAP` and `AuthenticationType.Transient` credentials.

**Comment by postlund** [comment]
> ```
> 2023-06-09 14:25:55 DEBUG [pyatv.protocols.airplay.auth]: Setting up new AirPlay Pair-Verify procedure with type AuthenticationType.Legacy
> ```
> 
> It looks like you've provided legacy credentials, I've only tried it with `AuthenticationType.HAP` credentials or no credentials for `AuthenticationType.Transient` (HomePod).

Bah, that was it of course 😄 Works great now!

**Pull request merged**
