### PR TITLE
Deprecate python 3.4, support 3.7 and fix some bugs

### PR DESCRIPTION
**Pull request by postlund**
This PR became a large one just because I was lazy enough to fix things properly. The following things changed:

aiohttp does not support python 3.4 in newer versions which results in
a lot of problems when dealing with that version (async/await are not
supported in python 3.4 which aiohttp uses). So this commit
unfortunately deprecates support for python 3.4 in order to make it
possible to maintain.

No syntax migration has been made, i.e. using async/await syntax, but
that switch has already been made on master.

This commit also fixes some asyncio errors mentioned in #150 as well
as #151.

netifaces has been added as a dependency, so #160 should be fixed now.

It is possible to specify "none" as pin code when pairing to skip pin code validation and allow any pin code.

### CODE REVIEW

**Comment by NebzHB** [comment]
ok for me

before update : 
`pi@Jeedom:~ $ atvremote -a down
/home/pi/.local/lib/python3.5/site-packages/pyatv/internal/apple_tv.py:509: Runt                                                   imeWarning: coroutine 'ClientSession.close' was never awaited
  self._session.close()
ERROR: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x75d4fbb0>
ERROR: Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x75f28970>, 11                                                   90310.432142204)]']
connector: <aiohttp.connector.TCPConnector object at 0x75d4fdf0>
`

after : 
`
pi@Jeedom:~ $ atvremote -a down
ERROR: Could not find any Apple TV on current network
pi@Jeedom:~ $ atvremote scan
Device "Salon (2)" at 192.168.1.70 supports these services:
 - Protocol: AirPlay, Port: 7000

Device "Salon" at 192.168.1.66 supports these services:
 - Protocol: DMAP, Port: 3689, Device Credentials: 00000000-1111-1111-1111-41788                                                   5114675
 - Protocol: MRP, Port: 49152, Device Credentials: None
 - Protocol: AirPlay, Port: 7000

Device "My Music on NAS" at 192.168.1.73 supports these services:
 - Protocol: DMAP, Port: 3689, Device Credentials: None

Device "Cuisine" at 192.168.1.71 supports these services:
 - Protocol: AirPlay, Port: 7000

Note: You must use 'pair' with devices that have home sharing disabled
pi@Jeedom:~ $ atvremote -a down
pi@Jeedom:~ $
`

**Comment by postlund** [comment]
It looks like you are running from master branch? The fixes are on release_0_3_x.

**Comment by NebzHB** [comment]
no i ran on the #fix_bugs branch

**Comment by postlund** [comment]
No, that's not correct. You should probably use git+https://github.com/postlund/pyatv@fix_bugs as address when doing that (but I have never used pip myself like that, so I'm not entirely sure). You can verify version with `atvremote --version` and it should say 0.3.11, but I belive you will see 0.4.0. The big give away here is that 0.3.x has no idea about MRP, which printed in the scan output above.

**Comment by postlund** [comment]
Great, thanks! 😄

**Comment by NebzHB** [comment]
Examples are still doing that error message :-(
```
pi@Jeedom:/usr/local/lib/python3.5/dist-packages/examples $ python3 auto_connect                                                                                                                                                             .py
Currently playing:
Media type: Unknown
Play state: Idle
    Repeat: Off
   Shuffle: False
/home/pi/.local/lib/python3.5/site-packages/pyatv/internal/apple_tv.py:509: Runt                                                                                                                                                             imeWarning: coroutine 'ClientSession.close' was never awaited
  self._session.close()
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x75dc6f10>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x75f3a710>, 14                                                                                                                                                             3273.872033486)]']
connector: <aiohttp.connector.TCPConnector object at 0x75d57870>

```

**Comment by ehendrix23** [comment]
@postlund Do you have an ETA or so when you believe this pull will make it into a release?

**Pull request merged**
